# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CM-MARATHON-PM'
    workingDirectory: 'ProjectManagementAPI'
- task: Maven@3
  inputs:
    mavenPomFile: 'ProjectManagementAPI/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'ProjectManagementAPI/Dockerfile'
- task: Maven@3
  inputs:
    mavenPomFile: 'Email2/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'Email2/Dockerfile'
- task: ado-discord-webhook@1
  inputs:
    channelId: '960982706504757309'
    webhookKey: '02A2rjYhvQbKBqus-nl8-6tftlCGgreOA0SCR4iJpQNs9ZZvzM2P4sCQCrEhVZYKQ4TX'
    name: 'Azure'
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Microsoft_Azure.svg/1200px-Microsoft_Azure.svg.png'
    messageType: 'content'
    content: 'Build Update for CM-MARATHON-PM: https://dev.azure.com/revature-training-uta/cm-marathon-pm/_build'
