# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  displayName: 'SonarCloud Preparation'
  inputs:
    SonarCloud: 'MarathonSonar'
    organization: 'cm-marathon-pm'
    scannerMode: 'MSBuild'
    projectKey: 'CM-MARATHON-PM'
    projectName: 'CM-MARATHON-PM'
- task: Maven@3
  displayName: 'Marathon Maven Build & Test'
  inputs:
    mavenPomFile: 'ProjectManagementAPI/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    goals: 'sonar:sonar'

- task: SonarCloudPublish@1
  displayName:  'Sonar Quality Gate'
  inputs:
    pollingTimeoutSec: '100'

- task: Docker@2
  displayName: 'Marathon Docker'
  inputs:
    containerRegistry: 'MarathonDockerHub'
    repository: 'connormunro/project-management-api'
    command: 'buildAndPush'
    tags: |
      $(Build.BuildId)
      latest
    Dockerfile: 'ProjectManagementAPI/Dockerfile' 
- task: Maven@3
  displayName: 'Email API Maven Build'
  inputs:
    mavenPomFile: 'Email2/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: 'Email API Docker'
  inputs:
    containerRegistry: 'MarathonDockerHub'
    repository: 'connormunro/email-api'
    command: 'buildAndPush'
    tags: |
      $(Build.BuildId)
      latest
    Dockerfile: 'Email2/Dockerfile'
#- task: ado-discord-webhook@1
#  displayName: 'Discord Update'
#  inputs:
#    channelId: '960982706504757309'
#    webhookKey: '02A2rjYhvQbKBqus-nl8-6tftlCGgreOA0SCR4iJpQNs9ZZvzM2P4sCQCrEhVZYKQ4TX'
#    name: 'Azure'
#    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Microsoft_Azure.svg/1200px-Microsoft_Azure.svg.png'
#    messageType: 'content'
#    content: 'Build Update for CM-MARATHON-PM: https://dev.azure.com/revature-training-uta/cm-marathon-pm/_build'
