apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
  labels:
    app: email-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
        - image: connormunro/email-api
          imagePullPolicy: Always
          name: email-api
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-api
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
